<a href="https://colab.research.google.com/github/telyotarsyn/simple_llm_rag/blob/main/Simple_RAG_petproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!nvidia-smi

Mon Sep 14 20:09:31 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P0             26W /   70W |     607MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            9424      C   /usr/bin/python3                        604MiB |
+-----------------------------------------------------------------------------------------+

In [5]:
# Download PDF file
import os
import requests

# Get PDF document
pdf_path = "dune.pdf"

# Download PDF if it doesn't already exist
if not os.path.exists(pdf_path):
  print("File doesn't exist, downloading...")

  # The URL of the PDF you want to download
  url = "https://www.hetako.ee/kamp/ulme/Frank%20Herbert%20-%20Dune%201%20-%20Dune.pdf"

  # The local filename to save the downloaded file
  filename = pdf_path

  # Send a GET request to the URL
  response = requests.get(url)

  # Check if the request was successful
  if response.status_code == 200:
      # Open a file in binary write mode and save the content to it
      with open(filename, "wb") as file:
          file.write(response.content)
      print(f"The file has been downloaded and saved as {filename}")
  else:
      print(f"Failed to download the file. Status code: {response.status_code}")
else:
  print(f"File {pdf_path} exists.")

File dune.pdf exists.

In [6]:
# Perform Google Colab installs (if running in Google Colab)
import os

if "COLAB_GPU" in os.environ:
    print("[INFO] Running in Google Colab, installing requirements.")
    !pip install -U torch # requires torch 2.1.1+ (for efficient sdpa implementation)
    !pip install PyMuPDF # for reading PDFs with Python
    !pip install tqdm # for progress bars
    !pip install sentence-transformers # for embedding models
    !pip install accelerate # for quantization model loading
    !pip install bitsandbytes # for quantizing models (less storage space)

KeyboardInterrupt:

In [7]:
# Requires !pip install PyMuPDF, see: https://github.com/pymupdf/pymupdf
import fitz # (pymupdf, found this is better than pypdf for our use case, note: licence is AGPL-3.0, keep that in mind if you want to use any code commercially)
from tqdm.auto import tqdm # for progress bars, requires !pip install tqdm

def text_formatter(text: str) -> str:
    """Performs minor formatting on text."""
    cleaned_text = text.replace("\n", " ").strip() # note: this might be different for each doc (best to experiment)

    # Other potential text formatting functions can go here
    return cleaned_text

# Open PDF and get lines/pages
# Note: this only focuses on text, rather than images/figures etc
def open_and_read_pdf(pdf_path: str) -> list[dict]:
    """
    Opens a PDF file, reads its text content page by page, and collects statistics.

    Parameters:
        pdf_path (str): The file path to the PDF document to be opened and read.

    Returns:
        list[dict]: A list of dictionaries, each containing the page number
        (adjusted), character count, word count, sentence count, token count, and the extracted text
        for each page.
    """
    doc = fitz.open(pdf_path)  # open a document
    pages_and_texts = []
    for page_number, page in tqdm(enumerate(doc)):  # iterate the document pages
        text = page.get_text()  # get plain text encoded as UTF-8
        text = text_formatter(text)
        pages_and_texts.append({"page_number": page_number - 41,  # adjust page numbers since our PDF starts on page 42
                                "page_char_count": len(text),
                                "page_word_count": len(text.split(" ")),
                                "page_sentence_count_raw": len(text.split(". ")),
                                "page_token_count": len(text) / 4,  # 1 token = ~4 chars, see: https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them
                                "text": text})
    return pages_and_texts

pages_and_texts = open_and_read_pdf(pdf_path=pdf_path)
pages_and_texts[:2]

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

0it [00:00, ?it/s]

[{'page_number': -41,
  'page_char_count': 119,
  'page_word_count': 29,
  'page_sentence_count_raw': 1,
  'page_token_count': 29.75,
  'text': 'Converted to  Converted to  Converted to  Converted to “PDF PDF PDF PDF” by  ” by  ” by  ” by ->MKM< >MKM< >MKM< >MKM<-'},
 {'page_number': -40,
  'page_char_count': 2291,
  'page_word_count': 498,
  'page_sentence_count_raw': 24,
  'page_token_count': 572.75,
  'text': 'Dune  Frank Herbert    Copyright 1965    Book 1  DUNE    = = = = = =     A beginning is the time for taking the most delicate care that the balances are  correct. This every sister of the Bene Gesserit knows. To begin your study of  the life of Muad\'Dib, then, take care that you first place him in his time: born  in the 57th year of the Padishah Emperor, Shaddam IV. And take the most special  care that you locate Muad\'Dib in his place: the planet Arrakis. Do not be  deceived by the fact that he was born on Caladan and lived his first fifteen  years there. Arrakis, the planet known as Dune, is forever his place.  -from "Manual of Muad\'Dib" by the Princess Irulan        In the week before their departure to Arrakis, when all the final scurrying  about had reached a nearly unbearable frenzy, an old crone came to visit the  mother of the boy, Paul.      It was a warm night at Castle Caladan, and the ancient pile of stone that  had served the Atreides family as home for twenty-six generations bore that  cooled-sweat feeling it acquired before a change in the weather.      The old woman was let in by the side door down the vaulted passage by Paul\'s  room and she was allowed a moment to peer in at him where he lay in his bed.      By the half-light of a suspensor lamp, dimmed and hanging near the floor,  the awakened boy could see a bulky female shape at his door, standing one step  ahead of his mother. The old woman was a witch shadow -- hair like matted  spiderwebs, hooded \'round darkness of features, eyes like glittering jewels.      "Is he not small for his age, Jessica?" the old woman asked. Her voice  wheezed and twanged like an untuned baliset.      Paul\'s mother answered in her soft contralto: "The Atreides are known to  start late getting their growth, Your Reverence."       "So I\'ve heard, so I\'ve heard," wheezed the old woman. "Yet he\'s already  fifteen."       "Yes, Your Reverence."      "He\'s awake and listening to us," said the old woman. "Sly little rascal."  She chuckled. "But royalty has need of slyness. And if he\'s really the Kwisatz  Haderach . . . well . . ."       Within the shadows of his bed, Paul held his eyes open to mere slits. Two  bird-bright ovals -- the eyes of the old woman -- seemed to expand and glow as  they stared into his.'}]

In [8]:
import random

random.sample(pages_and_texts, k=3)

[{'page_number': 41,
  'page_char_count': 3536,
  'page_word_count': 700,
  'page_sentence_count_raw': 40,
  'page_token_count': 884.0,
  'text': 'And Kynes, returning the stare, found himself troubled by a fact he had  observed here: This Duke was concerned more over the men that he was over the  spice. He risked his own life and that of his son to save the men. He passed off  the loss of a spice crawler with a gesture. The threat to men\'s lives had him in  a rage. A leader such as that would command fanatic loyalty. He would be  difficult to defeat.      Against his own will and all previous judgments, Kynes admitted to himself:  I like this Duke.    = = = = = =    Greatness is a transitory experience. It is never consistent. It depends in part  upon the myth-making imagination of humankind. The person who experiences  greatness must have a feeling for the myth he is in. He must reflect what is  projected upon him. And he must have a strong sense of the sardonic. This is  what uncouples him from belief in his own pretensions. The sardonic is all that  permits him to move within himself. Without this quality, even occasional  greatness will destroy a man.  -from "Collected Sayings of Muad\'Dib" by the Princess Irulan        In the dining hall of the Arrakeen great house, suspensor lamps had been  lighted against the early dark. They cast their yellow glows upward onto the  black bull\'s head with its bloody horns, and onto the darkly glistening oil  painting of the Old Duke.      Beneath these talismans, white linen shone around the burnished reflections  of the Atreides silver, which had been placed in precise arrangements along the  great table--little archipelagos of service waiting beside crystal glasses, each  setting squared off before a heavy wooden chair. The classic central chandelier  remained unlighted, and its chain twisted upward into shadows where the  mechanism of the poison-snooper had been concealed.      Pausing in the doorway to inspect the arrangements, the Duke thought about  the poison-snooper and what it signified in his society.      All of a pattern, he thought. You can plumb us by our language--the precise  and delicate delineations for ways to administer treacherous death. Will someone  try chaumurky tonight--poison in the drink? Or will it be chaumas--poison in the  food?      He shook his head.      Beside each plate on the long table stood a flagon of water. There was  enough water along the table, the Duke estimated, to keep a poor Arrakeen family  for more than a year.      Flanking the doorway in which he stood were broad laving basins of ornate  yellow and green tile. Each basin had its rack of towels. It was the custom, the  housekeeper had explained, for guests as they entered to dip their hands  ceremoniously into a basin, slop several cups of water onto the floor, dry their  hands on a towel and fling the towel into the growing puddle at the door. After  the dinner, beggars gathered outside to get the water squeezings from the  towels.      How typical of a Harkonnen fief, the Duke thought. Every degradation of the  spirit that can be conceived. He took a deep breath, feeling rage tighten his  stomach.       "The custom stops here!" he muttered.      He saw a serving woman--one of the old and gnarled ones the housekeeper had  recommended--hovering at the doorway from the kitchen across from him. The Duke  signaled with upraised hand. She moved out of the shadows, scurried around the  table toward him, and he noted the leathery face, the blue-within-blue eyes.       "My Lord wishes?" She kept her head bowed, eyes shielded.       He gestured. "Have these basins and towels removed."'},
 {'page_number': 97,
  'page_char_count': 3468,
  'page_word_count': 791,
  'page_sentence_count_raw': 54,
  'page_token_count': 867.0,
  'text': '"Why did you not say at first it was a water matter?" The Fremen stood up,  seated his nose plugs firmly.      Hawat motioned with his head for his aide to return to the others. With a  tired shrug, the man obeyed. Hawat heard a low-voiced conversation arise among  the men.      The Fremen said: "There is always a way to water."       Behind Hawat, a man cursed. Hawat\'s aide called: "Thufir! Arkie just died."      The Fremen put a fist to his ear. "The bond of water! It\'s a sign!" He  stared at Hawat. "We have a place nearby for accepting the water. Shall I call  my men?"      The aide returned to Hawat\'s side, said: "Thufir, a couple of the men left  wives in Arrakeen. They\'re . . . well, you know how it is at a time like this."      The Fremen still held his fist to his ear. "Is it the bond of water, Thufir  Hawat?" he demanded.      Hawat\'s mind was racing. He sensed now the direction of the Fremen\'s words,  but feared the reaction of the tired men under the rock overhang when they  understood it.       "The bond of water," Hawat said.      "Let our tribes be joined," the Fremen said, and he lowered his fist.      As though that were the signal, four men slid and dropped down from the  rocks above them. They darted back under the overhang, rolled the dead man in a  loose robe, lifted him and began running with him along the cliff wall to the  right. Spurts of dust lifted around their running feet.      It was over before Hawat\'s tired men could gather their wits. The group with  the body hanging like a sack in its enfolding robe was gone around a turn in the  cliff.      One of Hawat\'s men shouted: "Where they going with Arkie? He was--"       "They\'re taking him to . . . bury him," Hawat said.       "Fremen don\'t bury their dead!" the man barked. "Don\'t you try any tricks on  us, Thufir. We know what they do. Arkie was one of--"      "Paradise were sure for a man who died in the service of Lisan al-Gaib," the  Fremen said. "If it is the Lisan al-Gaib you serve, as you have said it, why  raise mourning cries? The memory of one who died in this fashion will live as  long as the memory of man endures."      But Hawat\'s men advanced, angry looks on their faces. One had captured a  lasgun. He started to draw it.      "Stop right where you are!" Hawat barked. He fought down the sick fatigue  that gripped his muscles. "These people respect our dead. Customs differ, but  the meaning\'s the same."       "They\'re going to render Arkie down for his water," the man with the lasgun  snarled.      "Is it that your men wish to attend the ceremony?" the Fremen asked.      He doesn\'t even see the problem, Hawat thought. The naivete of the Fremen  was frightening.      "They\'re concerned for a respected comrade," Hawat said.      "We will treat your comrade with the same reverence we treat our own," the  Fremen said. "This is the bond of water. We know the rites. A man\'s flesh is his  own; the water belongs to the tribe."       Hawat spoke quickly as the man with the lasgun advanced another step. "Will  you now help our wounded?"       "One does not question the bond," the Fremen said. "We will do for you what  a tribe does for its own. First, we must get all of you suited and see to the  necessities."       The man with the lasgun hesitated.      Hawat\'s aide said: "Are we buying help with Arkie\'s . . . water?"       "Not buying," Hawat said. "We\'ve joined these people."       "Customs differ," one of his men muttered.'},
 {'page_number': 48,
  'page_char_count': 3668,
  'page_word_count': 760,
  'page_sentence_count_raw': 45,
  'page_token_count': 917.0,
  'text': '"Do you mean, sir, that these birds are cannibals?"       "That\'s an odd question, young Master," the banker said. "I merely said the  birds drink blood. It doesn\'t have to be the blood of their own kind, does it?"      "It was not an odd question," Paul said, and Jessica noted the brittle  riposte quality of her training exposed in his voice. "Most educated people know  that the worst potential competition for any young organism can come from its  own kind." He deliberately forked a bite of food from his companion\'s plate, ate  it. "They are eating from the same bowl. They have the same basic requirements."       The banker stiffened, scowled at the Duke.      "Do not make the error of considering my son a child," the Duke said. And he  smiled.      Jessica glanced around the table, noted that Bewt had brightened, that both  Kynes and the smuggler, Tuek, were grinning.      "It\'s a rule of ecology," Kynes said, "that the young Master appears to  understand quite well. The struggle between life elements is the struggle for  the free energy of a system. Blood\'s an efficient energy source."      The banker put down his fork, spoke in an angry voice: "It\'s said that the  Fremen scum drink the blood of their dead."       Kynes shook his head, spoke in a lecturing tone: "Not the blood, sir. But  all of a man\'s water, ultimately, belongs to his people--to his tribe. It\'s a  necessity when you live near the Great Flat. All water\'s precious there, and the  human body is composed of some seventy per cent water by weight. A dead man,  surely, no longer requires that water."      The banker put both hands against the table beside his plate, and Jessica  thought he was going to push himself back, leave in a rage.      Kynes looked at Jessica. "Forgive me, my Lady, for elaborating on such an  ugly subject at table, but you were being told falsehood and it needed  clarifying."      "You\'ve associated so long with Fremen that you\'ve lost all sensibilities,"  the banker rasped.      Kynes looked at him calmly, studied the pale, trembling face. "Are you  challenging me, sir?"      The banker froze. He swallowed, spoke stiffly: "Of course not. I\'d not so  insult our host and hostess."      Jessica heard the fear in the man\'s voice, saw it in his face, in his  breathing, in the pulse of a vein at his temple. The man was terrified of Kynes!      "Our host and hostess are quite capable of deciding for themselves when  they\'ve been insulted," Kynes said. "They\'re brave people who understand defense  of honor. We all may attest to their courage by the fact that they are here . .  . now . . . on Arrakis."      Jessica saw that Leto was enjoying this. Most of the others were not. People  all around the table sat poised for flight, hands out of sight under the table.  Two notable exceptions were Bewt, who was openly smiling at the banker\'s  discomfiture, and the smuggler, Tuek, who appeared to be watching Kynes for a  cue. Jessica saw that Paul was looking at Kynes in admiration.       "Well?" Kynes said.      "I meant no offense," the banker muttered. "If offense was taken, please  accept my apologies."      "Freely given, freely accepted," Kynes said. He smiled at Jessica, resumed  eating as though nothing had happened.      Jessica saw that the smuggler, too, had relaxed. She marked this: the man  had shown every aspect of an aide ready to leap to Kynes\' assistance. There  existed an accord of some sort between Kynes and Tuek.      Leto toyed with a fork, looked speculatively at Kynes. The Geologist\'s  manner indicated a change in attitude toward the House of Atreides. Kynes had  seemed colder on their trip over the desert.'}]

In [9]:
import pandas as pd

df = pd.DataFrame(pages_and_texts)
df.head()

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,text
0,-41,119,29,1,29.75,Converted to Converted to Converted to Conv...
1,-40,2291,498,24,572.75,Dune Frank Herbert Copyright 1965 Book ...
2,-39,3591,736,79,897.75,"""Sleep well, you sly little rascal,"" said the ..."
3,-38,3562,736,44,890.50,When dawn touched Paul's window sill with yell...
4,-37,3513,788,63,878.25,"Now, there was a man who appreciated the power..."

In [10]:
# Get stats
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count
count,345.00,345.00,345.00,345.00,345.00
mean,131.00,3500.50,740.63,46.57,875.13
std,99.74,364.47,79.78,12.04,91.12
min,-41.00,0.00,1.00,1.00,0.00
25%,45.00,3406.00,727.00,40.00,851.50
50%,131.00,3536.00,754.00,46.00,884.00
75%,217.00,3668.00,777.00,51.00,917.00
max,303.00,4169.00,837.00,130.00,1042.25

In [11]:
from spacy.lang.en import English # see https://spacy.io/usage for install instructions

nlp = English()

# Add a sentencizer pipeline, see https://spacy.io/api/sentencizer/
nlp.add_pipe("sentencizer")

# Create a document instance as an example
doc = nlp("This is a sentence. This another sentence.")
assert len(list(doc.sents)) == 2

# Access the sentences of the document
list(doc.sents)

[This is a sentence., This another sentence.]

In [12]:
for item in tqdm(pages_and_texts):
    item["sentences"] = list(nlp(item["text"]).sents)

    # Make sure all sentences are strings
    item["sentences"] = [str(sentence) for sentence in item["sentences"]]

    # Count the sentences
    item["page_sentence_count_spacy"] = len(item["sentences"])
    # Inspect an example
random.sample(pages_and_texts, k=1)

  0%|          | 0/345 [00:00<?, ?it/s]

[{'page_number': 110,
  'page_char_count': 3688,
  'page_word_count': 777,
  'page_sentence_count_raw': 63,
  'page_token_count': 922.0,
  'text': '"I\'m sure we can produce an emergency to draw off any unwanted observers,  Nefud."      "I understand, m\'Lord. That\'s when Kynes can have his accident."      "Both Kynes and Hawat will have accidents then, Nefud. But only Kynes will  have a real accident. It\'s Hawat I want. Yes. Ah, yes."      Nefud blinked, swallowed. He appeared about to ask a question, but remained  silent.      "Hawat will be given both food and drink," the Baron said. "Treated with  kindness, with sympathy. In his water you will administer the residual poison  developed by the late Piter de Vries. And you will see that the antidote becomes  a regular part of Hawat\'s diet from this point on . . . unless I say otherwise."       "The antidote, yes." Nefud shook his head. "But--"       "Don\'t be dense, Nefud. The Duke almost killed me with that poison-capsule  tooth. The gas he exhaled into my presence deprived me of my most valuable  Mentat, Piter. I need a replacement."       "Hawat?"       "Hawat."       "But--"      "You\'re going to say Hawat\'s completely loyal to the Atreides. True, but the  Atreides are dead. We will woo him. He must be convinced he\'s not to blame for  the Duke\'s demise. It was all the doing of that Bene Gesserit witch. He had an  inferior master, one whose reason was clouded by emotion. Mentats admire the  ability to calculate without emotion, Nefud. We will woo the formidable Thufir  Hawat."       "Woo him. Yes, m\'Lord."      "Hawat, unfortunately, had a master whose resources were poor, one who could  not elevate a Mentat to the sublime peaks of reasoning that are a Mentat\'s  right. Hawat will see a certain element of truth in this. The Duke couldn\'t  afford the most efficient spies to provide his Mentat with the required  information." The Baron stared at Nefud. "Let us never deceive ourselves, Nefud.  The truth is a powerful weapon. We know how we overwhelmed the Atreides. Hawat  knows, too. We did it with wealth."       "With wealth. Yes, m\'Lord."      "We will woo Hawat," the Baron said. "We will hide him from the Sardaukar.  And we will hold in reserve . . . the withdrawal of the antidote for the poison.  There\'s no way of removing the residual poison. And, Nefud, Hawat need never  suspect. The antidote will not betray itself to a poison snooper. Hawat can scan  his food as he pleases and detect no trace of poison."       Nefud\'s eyes opened wide with understanding.      "The absence of a thing," the Baron said, "this can be as deadly as the  presence. The absence of air, eh? The absence of water? The absence of anything  else we\'re addicted to." The Baron nodded. "You understand me, Nefud?"       Nefud swallowed. "Yes, m\'Lord."      Then get busy. Find the Sardaukar commander and set things in motion."       "At once, m\'Lord." Nefud bowed, turned, and hurried away.      Hawat by my side! the Baron thought. The Sardaukar will give him to me. If  they suspect anything at all it\'s that I wish to destroy the Mentat. And this  suspicion I\'ll confirm! The fools! One of the most formidable Mentats in all  history, a Mentat trained to kill, and they\'ll toss him to me like some silly  toy to be broken. I will show them what use can be made of such a toy.      The Baron reached beneath a drapery beside his suspensor bed, pressed a  button to summon his older nephew, Rabban. He sat back, smiling.      And all the Atreides dead!      The stupid guard captain had been right, of course. Certainly, nothing  survived in the path of a sandblast storm on Arrakis. Not an ornithopter . . .  or its occupants. The woman and the boy were dead. The bribes in the right  places, the unthinkable expenditure to bring overwhelming military force down',
  'sentences': ['"I\'m sure we can produce an emergency to draw off any unwanted observers,  Nefud."',
   '     "I understand, m\'Lord.',
   'That\'s when Kynes can have his accident."',
   '     "Both Kynes and Hawat will have accidents then, Nefud.',
   'But only Kynes will  have a real accident.',
   "It's Hawat I want.",
   'Yes.',
   'Ah, yes."',
   '     Nefud blinked, swallowed.',
   'He appeared about to ask a question, but remained  silent.',
   '     "Hawat will be given both food and drink," the Baron said. "',
   'Treated with  kindness, with sympathy.',
   'In his water you will administer the residual poison  developed by the late Piter de Vries.',
   "And you will see that the antidote becomes  a regular part of Hawat's diet from this point on . . .",
   'unless I say otherwise."',
   '      "The antidote, yes."',
   'Nefud shook his head. "',
   'But--"       "Don\'t be dense, Nefud.',
   'The Duke almost killed me with that poison-capsule  tooth.',
   'The gas he exhaled into my presence deprived me of my most valuable  Mentat, Piter.',
   'I need a replacement."',
   '      "Hawat?"',
   '      "Hawat."',
   '      "But--"      "You\'re going to say Hawat\'s completely loyal to the Atreides.',
   'True, but the  Atreides are dead.',
   'We will woo him.',
   "He must be convinced he's not to blame for  the Duke's demise.",
   'It was all the doing of that Bene Gesserit witch.',
   'He had an  inferior master, one whose reason was clouded by emotion.',
   'Mentats admire the  ability to calculate without emotion, Nefud.',
   'We will woo the formidable Thufir  Hawat."',
   '      "Woo him.',
   'Yes, m\'Lord."',
   '     "Hawat, unfortunately, had a master whose resources were poor, one who could  not elevate a Mentat to the sublime peaks of reasoning that are a Mentat\'s  right.',
   'Hawat will see a certain element of truth in this.',
   'The Duke couldn\'t  afford the most efficient spies to provide his Mentat with the required  information."',
   'The Baron stared at Nefud. "',
   'Let us never deceive ourselves, Nefud.',
   ' The truth is a powerful weapon.',
   'We know how we overwhelmed the Atreides.',
   'Hawat  knows, too.',
   'We did it with wealth."',
   '      "With wealth.',
   'Yes, m\'Lord."',
   '     "We will woo Hawat," the Baron said. "',
   'We will hide him from the Sardaukar.',
   ' And we will hold in reserve . . .',
   'the withdrawal of the antidote for the poison.',
   " There's no way of removing the residual poison.",
   'And, Nefud, Hawat need never  suspect.',
   'The antidote will not betray itself to a poison snooper.',
   'Hawat can scan  his food as he pleases and detect no trace of poison."',
   "      Nefud's eyes opened wide with understanding.",
   '     "The absence of a thing," the Baron said, "this can be as deadly as the  presence.',
   'The absence of air, eh?',
   'The absence of water?',
   'The absence of anything  else we\'re addicted to."',
   'The Baron nodded. "',
   'You understand me, Nefud?"',
   '      Nefud swallowed. "',
   'Yes, m\'Lord."',
   '     Then get busy.',
   'Find the Sardaukar commander and set things in motion."',
   '      "At once, m\'Lord."',
   'Nefud bowed, turned, and hurried away.',
   '     Hawat by my side!',
   'the Baron thought.',
   'The Sardaukar will give him to me.',
   "If  they suspect anything at all it's that I wish to destroy the Mentat.",
   "And this  suspicion I'll confirm!",
   'The fools!',
   "One of the most formidable Mentats in all  history, a Mentat trained to kill, and they'll toss him to me like some silly  toy to be broken.",
   'I will show them what use can be made of such a toy.',
   '     The Baron reached beneath a drapery beside his suspensor bed, pressed a  button to summon his older nephew, Rabban.',
   'He sat back, smiling.',
   '     And all the Atreides dead!',
   '     The stupid guard captain had been right, of course.',
   'Certainly, nothing  survived in the path of a sandblast storm on Arrakis.',
   'Not an ornithopter . . .',
   ' or its occupants.',
   'The woman and the boy were dead.',
   'The bribes in the right  places, the unthinkable expenditure to bring overwhelming military force down'],
  'page_sentence_count_spacy': 82}]

In [13]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy
count,345.00,345.00,345.00,345.00,345.00,345.00
mean,131.00,3500.50,740.63,46.57,875.13,56.37
std,99.74,364.47,79.78,12.04,91.12,12.27
min,-41.00,0.00,1.00,1.00,0.00,0.00
25%,45.00,3406.00,727.00,40.00,851.50,50.00
50%,131.00,3536.00,754.00,46.00,884.00,57.00
75%,217.00,3668.00,777.00,51.00,917.00,64.00
max,303.00,4169.00,837.00,130.00,1042.25,89.00

In [14]:
# Define split size to turn groups of sentences into chunks
num_sentence_chunk_size = 10

# Create a function that recursively splits a list into desired sizes
def split_list(input_list: list,
               slice_size: int) -> list[list[str]]:
    """
    Splits the input_list into sublists of size slice_size (or as close as possible).

    For example, a list of 17 sentences would be split into two lists of [[10], [7]]
    """
    return [input_list[i:i + slice_size] for i in range(0, len(input_list), slice_size)]

# Loop through pages and texts and split sentences into chunks
for item in tqdm(pages_and_texts):
    item["sentence_chunks"] = split_list(input_list=item["sentences"],
                                         slice_size=num_sentence_chunk_size)
    item["num_chunks"] = len(item["sentence_chunks"])
# Sample an example from the group (note: many samples have only 1 chunk as they have <=10 sentences total)
random.sample(pages_and_texts, k=1)

  0%|          | 0/345 [00:00<?, ?it/s]

[{'page_number': 248,
  'page_char_count': 3778,
  'page_word_count': 816,
  'page_sentence_count_raw': 59,
  'page_token_count': 944.5,
  'text': 'terror. Without knowing why, her whole being trembled at what she had seen -- a  region where a wind blew and sparks glared, where rings of light expanded and  contracted, where rows of tumescent white shapes flowed over and under and  around the lights, driven by darkness and a wind out of nowhere.      Presently, she opened her eyes, saw Paul staring up at her. He still held  her hand, but the terrible rapport was gone. She quieted her trembling. Paul  released her hand. It was as though some crutch had been removed. She staggered  up and back, would have fallen had not Chani jumped to support her.      "Reverend Mother!" Chani said. "What is wrong?"       "Tired," Jessica whispered. "So . . . tired."      "Here," Chani said. "Sit here." She helped Jessica to a cushion against the  wall.      The strong young arms felt so good to Jessica. She clung to Chani.      "He has, in truth, seen the Water of Life?" Chani asked. She disengaged  herself from Jessica\'s grip.      "He has seen," Jessica whispered. Her mind still rolled and surged from the  contact. It was like stepping to solid land after weeks on a heaving sea. She  sensed the old Reverend Mother within her . . . and all the others awakened and  questioning; "What was that? What happened? Where was that place?"      Through it all threaded the realization that her son was the Kwisatz  Haderach, the one who could be many places at once. He was the fact out of the  Bene Gesserit dream. And the fact gave her no peace.      "What happened?" Chani demanded.       Jessica shook her head.      Paul said: "There is in each of us an ancient force that takes and an  ancient force that gives. A man finds little difficulty facing that place within  himself where the taking force dwells, but it\'s almost impossible for him to see  into the giving force without changing into something other than man. For a  woman, the situation is reversed."       Jessica looked up, found Chani was staring at her while listening to Paul.      "Do you understand me, Mother?" Paul asked.       She could only nod.      "These things are so ancient within us," Paul said, "that they\'re ground  into each separate cell of our bodies. We\'re shaped by such forces. You can say  to yourself, \'Yes, I see how such a thing may be.\' But when you look inward and  confront the raw force of your own life unshielded, you see your peril. You see  that this could overwhelm you. The greatest peril to the Giver is the force that  takes. The greatest peril to the Taker is the force that gives. It\'s as easy to  be overwhelmed by giving as by taking."       "And you, my son," Jessica asked, "are you one who gives or one who takes?"      "I\'m at the fulcrum," he said. "I cannot give without taking and I cannot  take without . . . " He broke off, looking to the wall at his right.      Chani felt a draft against her cheek, turned to see the hangings close.      "It was Otheym," Paul said. "He was listening."       Accepting the words, Chani was touched by some of the prescience that  haunted Paul, and she knew a thing-yet-to-be as though it already had occurred.  Otheym would speak of what he had seen and heard. Others would spread the story  until it was a fire over the land. Paul-Muad\'Dib is not as other men, they would  say. There can be no more doubt. He is a man, yet he sees through to the Water  of Life in the way of a Reverend Mother. He is indeed the Lisan al-Gaib.      "You have seen the future, Paul," Jessica said. "Will you say what you\'ve  seen?"      "Not the future," he said. "I\'ve seen the Now." He forced himself to a  sitting position, waved Chani aside as she moved to help him. "The Space above  Arrakis is filled with the ships of the Guild."       Jessica trembled at the certainty in his voice.',
  'sentences': ['terror.',
   'Without knowing why, her whole being trembled at what she had seen -- a  region where a wind blew and sparks glared, where rings of light expanded and  contracted, where rows of tumescent white shapes flowed over and under and  around the lights, driven by darkness and a wind out of nowhere.',
   '     Presently, she opened her eyes, saw Paul staring up at her.',
   'He still held  her hand, but the terrible rapport was gone.',
   'She quieted her trembling.',
   'Paul  released her hand.',
   'It was as though some crutch had been removed.',
   'She staggered  up and back, would have fallen had not Chani jumped to support her.',
   '     "Reverend Mother!"',
   'Chani said. "',
   'What is wrong?"',
   '      "Tired," Jessica whispered. "',
   'So . . .',
   'tired."',
   '     "Here," Chani said. "',
   'Sit here."',
   'She helped Jessica to a cushion against the  wall.',
   '     The strong young arms felt so good to Jessica.',
   'She clung to Chani.',
   '     "He has, in truth, seen the Water of Life?"',
   'Chani asked.',
   "She disengaged  herself from Jessica's grip.",
   '     "He has seen," Jessica whispered.',
   'Her mind still rolled and surged from the  contact.',
   'It was like stepping to solid land after weeks on a heaving sea.',
   'She  sensed the old Reverend Mother within her . . .',
   'and all the others awakened and  questioning; "What was that?',
   'What happened?',
   'Where was that place?"',
   '     Through it all threaded the realization that her son was the Kwisatz  Haderach, the one who could be many places at once.',
   'He was the fact out of the  Bene Gesserit dream.',
   'And the fact gave her no peace.',
   '     "What happened?"',
   'Chani demanded.',
   '      Jessica shook her head.',
   '     Paul said: "There is in each of us an ancient force that takes and an  ancient force that gives.',
   "A man finds little difficulty facing that place within  himself where the taking force dwells, but it's almost impossible for him to see  into the giving force without changing into something other than man.",
   'For a  woman, the situation is reversed."',
   '      Jessica looked up, found Chani was staring at her while listening to Paul.',
   '     "Do you understand me, Mother?"',
   'Paul asked.',
   '      She could only nod.',
   '     "These things are so ancient within us," Paul said, "that they\'re ground  into each separate cell of our bodies.',
   "We're shaped by such forces.",
   "You can say  to yourself, 'Yes, I see how such a thing may be.'",
   'But when you look inward and  confront the raw force of your own life unshielded, you see your peril.',
   'You see  that this could overwhelm you.',
   'The greatest peril to the Giver is the force that  takes.',
   'The greatest peril to the Taker is the force that gives.',
   'It\'s as easy to  be overwhelmed by giving as by taking."',
   '      "And you, my son," Jessica asked, "are you one who gives or one who takes?"',
   '     "I\'m at the fulcrum," he said. "',
   'I cannot give without taking and I cannot  take without . . . "',
   'He broke off, looking to the wall at his right.',
   '     Chani felt a draft against her cheek, turned to see the hangings close.',
   '     "It was Otheym," Paul said. "',
   'He was listening."',
   '      Accepting the words, Chani was touched by some of the prescience that  haunted Paul, and she knew a thing-yet-to-be as though it already had occurred.',
   ' Otheym would speak of what he had seen and heard.',
   'Others would spread the story  until it was a fire over the land.',
   "Paul-Muad'Dib is not as other men, they would  say.",
   'There can be no more doubt.',
   'He is a man, yet he sees through to the Water  of Life in the way of a Reverend Mother.',
   'He is indeed the Lisan al-Gaib.',
   '     "You have seen the future, Paul," Jessica said. "',
   'Will you say what you\'ve  seen?"',
   '     "Not the future," he said. "',
   'I\'ve seen the Now."',
   'He forced himself to a  sitting position, waved Chani aside as she moved to help him. "',
   'The Space above  Arrakis is filled with the ships of the Guild."',
   '      Jessica trembled at the certainty in his voice.'],
  'page_sentence_count_spacy': 71,
  'sentence_chunks': [['terror.',
    'Without knowing why, her whole being trembled at what she had seen -- a  region where a wind blew and sparks glared, where rings of light expanded and  contracted, where rows of tumescent white shapes flowed over and under and  around the lights, driven by darkness and a wind out of nowhere.',
    '     Presently, she opened her eyes, saw Paul staring up at her.',
    'He still held  her hand, but the terrible rapport was gone.',
    'She quieted her trembling.',
    'Paul  released her hand.',
    'It was as though some crutch had been removed.',
    'She staggered  up and back, would have fallen had not Chani jumped to support her.',
    '     "Reverend Mother!"',
    'Chani said. "'],
   ['What is wrong?"',
    '      "Tired," Jessica whispered. "',
    'So . . .',
    'tired."',
    '     "Here," Chani said. "',
    'Sit here."',
    'She helped Jessica to a cushion against the  wall.',
    '     The strong young arms felt so good to Jessica.',
    'She clung to Chani.',
    '     "He has, in truth, seen the Water of Life?"'],
   ['Chani asked.',
    "She disengaged  herself from Jessica's grip.",
    '     "He has seen," Jessica whispered.',
    'Her mind still rolled and surged from the  contact.',
    'It was like stepping to solid land after weeks on a heaving sea.',
    'She  sensed the old Reverend Mother within her . . .',
    'and all the others awakened and  questioning; "What was that?',
    'What happened?',
    'Where was that place?"',
    '     Through it all threaded the realization that her son was the Kwisatz  Haderach, the one who could be many places at once.'],
   ['He was the fact out of the  Bene Gesserit dream.',
    'And the fact gave her no peace.',
    '     "What happened?"',
    'Chani demanded.',
    '      Jessica shook her head.',
    '     Paul said: "There is in each of us an ancient force that takes and an  ancient force that gives.',
    "A man finds little difficulty facing that place within  himself where the taking force dwells, but it's almost impossible for him to see  into the giving force without changing into something other than man.",
    'For a  woman, the situation is reversed."',
    '      Jessica looked up, found Chani was staring at her while listening to Paul.',
    '     "Do you understand me, Mother?"'],
   ['Paul asked.',
    '      She could only nod.',
    '     "These things are so ancient within us," Paul said, "that they\'re ground  into each separate cell of our bodies.',
    "We're shaped by such forces.",
    "You can say  to yourself, 'Yes, I see how such a thing may be.'",
    'But when you look inward and  confront the raw force of your own life unshielded, you see your peril.',
    'You see  that this could overwhelm you.',
    'The greatest peril to the Giver is the force that  takes.',
    'The greatest peril to the Taker is the force that gives.',
    'It\'s as easy to  be overwhelmed by giving as by taking."'],
   ['      "And you, my son," Jessica asked, "are you one who gives or one who takes?"',
    '     "I\'m at the fulcrum," he said. "',
    'I cannot give without taking and I cannot  take without . . . "',
    'He broke off, looking to the wall at his right.',
    '     Chani felt a draft against her cheek, turned to see the hangings close.',
    '     "It was Otheym," Paul said. "',
    'He was listening."',
    '      Accepting the words, Chani was touched by some of the prescience that  haunted Paul, and she knew a thing-yet-to-be as though it already had occurred.',
    ' Otheym would speak of what he had seen and heard.',
    'Others would spread the story  until it was a fire over the land.'],
   ["Paul-Muad'Dib is not as other men, they would  say.",
    'There can be no more doubt.',
    'He is a man, yet he sees through to the Water  of Life in the way of a Reverend Mother.',
    'He is indeed the Lisan al-Gaib.',
    '     "You have seen the future, Paul," Jessica said. "',
    'Will you say what you\'ve  seen?"',
    '     "Not the future," he said. "',
    'I\'ve seen the Now."',
    'He forced himself to a  sitting position, waved Chani aside as she moved to help him. "',
    'The Space above  Arrakis is filled with the ships of the Guild."'],
   ['      Jessica trembled at the certainty in his voice.']],
  'num_chunks': 8}]

In [15]:
# Create a DataFrame to get stats
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy,num_chunks
count,345.00,345.00,345.00,345.00,345.00,345.00,345.00
mean,131.00,3500.50,740.63,46.57,875.13,56.37,6.10
std,99.74,364.47,79.78,12.04,91.12,12.27,1.26
min,-41.00,0.00,1.00,1.00,0.00,0.00,0.00
25%,45.00,3406.00,727.00,40.00,851.50,50.00,5.00
50%,131.00,3536.00,754.00,46.00,884.00,57.00,6.00
75%,217.00,3668.00,777.00,51.00,917.00,64.00,7.00
max,303.00,4169.00,837.00,130.00,1042.25,89.00,9.00

In [16]:
import re

# Split each chunk into its own item
pages_and_chunks = []
for item in tqdm(pages_and_texts):
    for sentence_chunk in item["sentence_chunks"]:
        chunk_dict = {}
        chunk_dict["page_number"] = item["page_number"]

        # Join the sentences together into a paragraph-like structure, aka a chunk (so they are a single string)
        joined_sentence_chunk = "".join(sentence_chunk).replace("  ", " ").strip()
        joined_sentence_chunk = re.sub(r'\.([A-Z])', r'. \1', joined_sentence_chunk) # ".A" -> ". A" for any full-stop/capital letter combo
        chunk_dict["sentence_chunk"] = joined_sentence_chunk

        # Get stats about the chunk
        chunk_dict["chunk_char_count"] = len(joined_sentence_chunk)
        chunk_dict["chunk_word_count"] = len([word for word in joined_sentence_chunk.split(" ")])
        chunk_dict["chunk_token_count"] = len(joined_sentence_chunk) / 4 # 1 token = ~4 characters

        pages_and_chunks.append(chunk_dict)

# How many chunks do we have?
len(pages_and_chunks)

  0%|          | 0/345 [00:00<?, ?it/s]

2104

In [17]:
# View a random sample
random.sample(pages_and_chunks, k=1)

[{'page_number': 130,
  'sentence_chunk': 'The hissing approach spread across the night behind them. They turned their heads as they walked, saw the mound of the coursing worm.   "Keep moving," Paul whispered. "Don\'t look back."   A grating sound of fury exploded from the rock shadows they had left. It was a flailing avalanche of noise.   "Keep moving," Paul repeating.',
  'chunk_char_count': 328,
  'chunk_word_count': 60,
  'chunk_token_count': 82.0}]

In [18]:
# Get stats about our chunks
df = pd.DataFrame(pages_and_chunks)
df.describe().round(2)

       page_number  chunk_char_count  chunk_word_count  chunk_token_count
count      2104.00           2104.00           2104.00            2104.00
mean        124.70            554.31            102.60             138.58
std          97.51            230.28             40.62              57.57
min         -41.00              2.00              1.00               0.50
25%          41.00            413.00             78.00             103.25
50%         121.00            530.00             99.00             132.50
75%         209.25            682.25            125.00             170.56
max         302.00           2024.00            335.00             506.00

In [19]:
# Show random chunks with under 30 tokens in length
min_token_length = 30
for row in df[df["chunk_token_count"] <= min_token_length].sample(5).iterrows():
    print(f'Chunk token count: {row[1]["chunk_token_count"]} | Text: {row[1]["sentence_chunk"]}')

Chunk token count: 3.25 | Text: questioning."
Chunk token count: 16.0 | Text: She nodded, letting him know that they left with her permission.
Chunk token count: 13.0 | Text: El-sayals frequently bring moisture to ground level.
Chunk token count: 27.75 | Text: "My Lord wishes?"She kept her head bowed, eyes shielded.   He gestured. "Have these basins and towels removed."
Chunk token count: 9.5 | Text: He stopped the circling, straightened.

In [20]:
pages_and_chunks_over_min_token_len = df[df["chunk_token_count"] > min_token_length].to_dict(orient="records")
pages_and_chunks_over_min_token_len[:2]

[{'page_number': -40,
  'sentence_chunk': 'Dune Frank Herbert  Copyright 1965  Book 1 DUNE  = = = = = =   A beginning is the time for taking the most delicate care that the balances are correct. This every sister of the Bene Gesserit knows. To begin your study of the life of Muad\'Dib, then, take care that you first place him in his time: born in the 57th year of the Padishah Emperor, Shaddam IV. And take the most special care that you locate Muad\'Dib in his place: the planet Arrakis. Do not be deceived by the fact that he was born on Caladan and lived his first fifteen years there. Arrakis, the planet known as Dune, is forever his place. -from "Manual of Muad\'Dib" by the Princess Irulan    In the week before their departure to Arrakis, when all the final scurrying about had reached a nearly unbearable frenzy, an old crone came to visit the mother of the boy, Paul.   It was a warm night at Castle Caladan, and the ancient pile of stone that had served the Atreides family as home for twenty-six generations bore that cooled-sweat feeling it acquired before a change in the weather.   The old woman was let in by the side door down the vaulted passage by Paul\'s room and she was allowed a moment to peer in at him where he lay in his bed.   By the half-light of a suspensor lamp, dimmed and hanging near the floor, the awakened boy could see a bulky female shape at his door, standing one step ahead of his mother.',
  'chunk_char_count': 1382,
  'chunk_word_count': 272,
  'chunk_token_count': 345.5},
 {'page_number': -40,
  'sentence_chunk': 'The old woman was a witch shadow -- hair like matted spiderwebs, hooded \'round darkness of features, eyes like glittering jewels.   "Is he not small for his age, Jessica?"the old woman asked. Her voice wheezed and twanged like an untuned baliset.   Paul\'s mother answered in her soft contralto: "The Atreides are known to start late getting their growth, Your Reverence."   "So I\'ve heard, so I\'ve heard," wheezed the old woman. "Yet he\'s already fifteen."   "Yes, Your Reverence."   "He\'s awake and listening to us," said the old woman. "Sly little rascal."',
  'chunk_char_count': 558,
  'chunk_word_count': 100,
  'chunk_token_count': 139.5}]

In [21]:
!pip install -q langchain-huggingface

In [2]:
import torch
import transformers
import langchain
import numpy as np

print(" Все ключевые библиотеки RAG успешно импортированы!")
print(f"PyTorch version: {torch.__version__}")
print(f"NumPy version: {np.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU device: {torch.cuda.get_device_name(0)}")

 Все ключевые библиотеки RAG успешно импортированы!
PyTorch version: 2.6.0+cu124
NumPy version: 2.5.2
CUDA available: True
GPU device: Tesla T4

In [25]:
!pip install torch torchvision --index-url https://download.pytorch.org/whl/cu124

Looking in indexes: https://download.pytorch.org/whl/cu124
Collecting torch
  Downloading https://download-r2.pytorch.org/whl/cu124/torch-2.6.0%2Bcu124-cp313-cp313-linux_x86_64.whl.metadata (28 kB)
Collecting torchvision
  Downloading https://download-r2.pytorch.org/whl/cu124/torchvision-0.21.0%2Bcu124-cp313-cp313-linux_x86_64.whl.metadata (6.1 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch) (3.32.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch) (4.16.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.13/dist-packages (from torch) (2025.12.0)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cuda-nvrtc-cu12/nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 102.2 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cuda-runtime-cu12/nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 226.3 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cuda-cupti-cu12/nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 141.6 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.9 MB/s eta 0:00:00
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 58.5 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cufft-cu12/nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 79.0 MB/s eta 0:00:00
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-curand-cu12/nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 91.0 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cusolver-cu12/nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 97.5 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cusparse-cu12/nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 88.3 MB/s eta 0:00:00
Collecting nvidia-cusparselt-cu12==0.6.2 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cusparselt-cu12/nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl (150.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.1/150.1 MB 101.5 MB/s eta 0:00:00
Collecting nvidia-nccl-cu12==2.21.5 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-nccl-cu12/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 13.9 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu12==12.4.127 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-nvtx-cu12/nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 122.5 MB/s eta 0:00:00
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-nvjitlink-cu12/nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 129.2 MB/s eta 0:00:00
Collecting triton==3.2.0 (from torch)
  Downloading https://download-r2.pytorch.org/whl/triton-3.2.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from torch) (80.10.2)
Collecting sympy==1.13.1 (from torch)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from torchvision) (2.1.3)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.13/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch) (3.0.3)
Downloading https://download-r2.pytorch.org/whl/cu124/torch-2.6.0%2Bcu124-cp313-cp313-linux_x86_64.whl (768.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 768.4/768.4 MB 1.2 MB/s eta 0:00:00
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 73.2 MB/s eta 0:00:00
Downloading https://download-r2.pytorch.org/whl/triton-3.2.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (166.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.7/166.7 MB 8.1 MB/s eta 0:00:00
Downloading https://download-r2.pytorch.org/whl/cu124/torchvision-0.21.0%2Bcu124-cp313-cp313-linux_x86_64.whl (7.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 86.3 MB/s eta 0:00:00
Installing collected packages: triton, nvidia-cusparselt-cu12, sympy, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch, torchvision
  Attempting uninstall: triton
    Found existing installation: triton 3.8.0
    Uninstalling triton-3.8.0:
      Successfully uninstalled triton-3.8.0
  Attempting uninstall: nvidia-cusparselt-cu12
    Found existing installation: nvidia-cusparselt-cu12 0.7.1
    Uninstalling nvidia-cusparselt-cu12-0.7.1:
      Successfully uninstalled nvidia-cusparselt-cu12-0.7.1
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.0
    Uninstalling sympy-1.14.0:
      Successfully uninstalled sympy-1.14.0
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.8.90
    Uninstalling nvidia-nvtx-cu12-12.8.90:
      Successfully uninstalled nvidia-nvtx-cu12-12.8.90
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.8.93
    Uninstalling nvidia-nvjitlink-cu12-12.8.93:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.8.93
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.28.9
    Uninstalling nvidia-nccl-cu12-2.28.9:
      Successfully uninstalled nvidia-nccl-cu12-2.28.9
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.9.90
    Uninstalling nvidia-curand-cu12-10.3.9.90:
      Successfully uninstalled nvidia-curand-cu12-10.3.9.90
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.3.3.83
    Uninstalling nvidia-cufft-cu12-11.3.3.83:
      Successfully uninstalled nvidia-cufft-cu12-11.3.3.83
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.8.90
    Uninstalling nvidia-cuda-runtime-cu12-12.8.90:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.8.90
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.8.93
    Uninstalling nvidia-cuda-nvrtc-cu12-12.8.93:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.8.93
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.8.90
    Uninstalling nvidia-cuda-cupti-cu12-12.8.90:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.8.90
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.8.4.1
    Uninstalling nvidia-cublas-cu12-12.8.4.1:
      Successfully uninstalled nvidia-cublas-cu12-12.8.4.1
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.8.93
    Uninstalling nvidia-cusparse-cu12-12.5.8.93:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.8.93
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.19.0.56
    Uninstalling nvidia-cudnn-cu12-9.19.0.56:
      Successfully uninstalled nvidia-cudnn-cu12-9.19.0.56
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.7.3.90
    Uninstalling nvidia-cusolver-cu12-11.7.3.90:
      Successfully uninstalled nvidia-cusolver-cu12-11.7.3.90
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
libraft-cu12 26.2.0 requires cuda-toolkit[cublas,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
libcuvs-cu12 26.2.0 requires cuda-toolkit[cublas,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-cusparselt-cu12-0.6.2 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 sympy-1.13.1 torch-2.6.0+cu124 torchvision-0.21.0+cu124 triton-3.2.0

In [22]:
!python -c "import torchvision; print(torchvision.__version__)"

0.21.0+cu124

In [30]:
!pip install --force-reinstall --no-input torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

Looking in indexes: https://download.pytorch.org/whl/cu124
Collecting torch
  Using cached https://download-r2.pytorch.org/whl/cu124/torch-2.6.0%2Bcu124-cp313-cp313-linux_x86_64.whl.metadata (28 kB)
Collecting torchvision
  Using cached https://download-r2.pytorch.org/whl/cu124/torchvision-0.21.0%2Bcu124-cp313-cp313-linux_x86_64.whl.metadata (6.1 kB)
Collecting torchaudio
  Downloading https://download-r2.pytorch.org/whl/cu124/torchaudio-2.6.0%2Bcu124-cp313-cp313-linux_x86_64.whl.metadata (6.6 kB)
Collecting filelock (from torch)
  Downloading filelock-3.32.3-py3-none-any.whl.metadata (2.0 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting networkx (from torch)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch)
  Downloading https://download.pytorch.org/whl/jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec (from torch)
  Downloading fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cuda-nvrtc-cu12/nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 136.8 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cuda-runtime-cu12/nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 238.4 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cuda-cupti-cu12/nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 143.0 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Using cached https://download.pytorch.org/whl/cu124/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 66.1 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cufft-cu12/nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 75.2 MB/s eta 0:00:00
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-curand-cu12/nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 117.7 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cusolver-cu12/nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 89.6 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cusparse-cu12/nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 82.7 MB/s eta 0:00:00
Collecting nvidia-cusparselt-cu12==0.6.2 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-cusparselt-cu12/nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl (150.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.1/150.1 MB 101.3 MB/s eta 0:00:00
Collecting nvidia-nccl-cu12==2.21.5 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-nccl-cu12/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 9.1 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu12==12.4.127 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-nvtx-cu12/nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 99.6 MB/s eta 0:00:00
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading https://pypi.nvidia.com/nvidia-nvjitlink-cu12/nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 106.1 MB/s eta 0:00:00
Collecting triton==3.2.0 (from torch)
  Using cached https://download-r2.pytorch.org/whl/triton-3.2.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.4 kB)
Collecting setuptools (from torch)
  Downloading https://download.pytorch.org/whl/setuptools-78.1.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy==1.13.1 (from torch)
  Using cached sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting numpy (from torchvision)
  Downloading numpy-2.5.2-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading https://download.pytorch.org/whl/markupsafe-3.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Using cached https://download-r2.pytorch.org/whl/cu124/torch-2.6.0%2Bcu124-cp313-cp313-linux_x86_64.whl (768.4 MB)
Using cached sympy-1.13.1-py3-none-any.whl (6.2 MB)
Using cached https://download-r2.pytorch.org/whl/triton-3.2.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (166.7 MB)
Using cached https://download-r2.pytorch.org/whl/cu124/torchvision-0.21.0%2Bcu124-cp313-cp313-linux_x86_64.whl (7.3 MB)
Downloading https://download-r2.pytorch.org/whl/cu124/torchaudio-2.6.0%2Bcu124-cp313-cp313-linux_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 6.1 MB/s eta 0:00:00
Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 61.8 MB/s eta 0:00:00
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 2.8 MB/s eta 0:00:00
Downloading filelock-3.32.3-py3-none-any.whl (98 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.9/98.9 kB 11.1 MB/s eta 0:00:00
Downloading fsspec-2026.7.0-py3-none-any.whl (206 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.6/206.6 kB 17.4 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/jinja2-3.1.6-py3-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 9.8 MB/s eta 0:00:00
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 85.3 MB/s eta 0:00:00
Downloading numpy-2.5.2-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 81.0 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/setuptools-78.1.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 65.1 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/markupsafe-3.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 28.0 MB/s eta 0:00:00
Installing collected packages: triton, nvidia-cusparselt-cu12, mpmath, typing-extensions, sympy, setuptools, pillow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, MarkupSafe, fsspec, filelock, nvidia-cusparse-cu12, nvidia-cudnn-cu12, jinja2, nvidia-cusolver-cu12, torch, torchvision, torchaudio
  Attempting uninstall: triton
    Found existing installation: triton 3.2.0
    Uninstalling triton-3.2.0:
      Successfully uninstalled triton-3.2.0
  Attempting uninstall: nvidia-cusparselt-cu12
    Found existing installation: nvidia-cusparselt-cu12 0.6.2
    Uninstalling nvidia-cusparselt-cu12-0.6.2:
      Successfully uninstalled nvidia-cusparselt-cu12-0.6.2
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:
      Successfully uninstalled mpmath-1.3.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
      Successfully uninstalled typing_extensions-4.16.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.1
    Uninstalling sympy-1.13.1:
      Successfully uninstalled sympy-1.13.1
  Attempting uninstall: setuptools
    Found existing installation: setuptools 80.10.2
    Uninstalling setuptools-80.10.2:
      Successfully uninstalled setuptools-80.10.2
  Attempting uninstall: pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.4.127
    Uninstalling nvidia-nvtx-cu12-12.4.127:
      Successfully uninstalled nvidia-nvtx-cu12-12.4.127
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.4.127
    Uninstalling nvidia-nvjitlink-cu12-12.4.127:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.4.127
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.21.5
    Uninstalling nvidia-nccl-cu12-2.21.5:
      Successfully uninstalled nvidia-nccl-cu12-2.21.5
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.5.147
    Uninstalling nvidia-curand-cu12-10.3.5.147:
      Successfully uninstalled nvidia-curand-cu12-10.3.5.147
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.1.3
    Uninstalling nvidia-cufft-cu12-11.2.1.3:
      Successfully uninstalled nvidia-cufft-cu12-11.2.1.3
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.4.127
    Uninstalling nvidia-cuda-runtime-cu12-12.4.127:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.4.127
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.4.127
    Uninstalling nvidia-cuda-nvrtc-cu12-12.4.127:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.4.127
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.4.127
    Uninstalling nvidia-cuda-cupti-cu12-12.4.127:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.4.127
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.4.5.8
    Uninstalling nvidia-cublas-cu12-12.4.5.8:
      Successfully uninstalled nvidia-cublas-cu12-12.4.5.8
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.3
    Uninstalling numpy-2.1.3:
      Successfully uninstalled numpy-2.1.3
  Attempting uninstall: networkx
    Found existing installation: networkx 3.6.1
    Uninstalling networkx-3.6.1:
      Successfully uninstalled networkx-3.6.1
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 3.0.3
    Uninstalling MarkupSafe-3.0.3:
      Successfully uninstalled MarkupSafe-3.0.3
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.12.0
    Uninstalling fsspec-2025.12.0:
      Successfully uninstalled fsspec-2025.12.0
  Attempting uninstall: filelock
    Found existing installation: filelock 3.32.5
    Uninstalling filelock-3.32.5:
      Successfully uninstalled filelock-3.32.5
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.3.1.170
    Uninstalling nvidia-cusparse-cu12-12.3.1.170:
      Successfully uninstalled nvidia-cusparse-cu12-12.3.1.170
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.1.0.70
    Uninstalling nvidia-cudnn-cu12-9.1.0.70:
      Successfully uninstalled nvidia-cudnn-cu12-9.1.0.70
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.1.6
    Uninstalling Jinja2-3.1.6:
      Successfully uninstalled Jinja2-3.1.6
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.1.9
    Uninstalling nvidia-cusolver-cu12-11.6.1.9:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.1.9
  Attempting uninstall: torch
    Found existing installation: torch 2.6.0+cu124
    Uninstalling torch-2.6.0+cu124:
      Successfully uninstalled torch-2.6.0+cu124
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.21.0+cu124
    Uninstalling torchvision-0.21.0+cu124:
      Successfully uninstalled torchvision-0.21.0+cu124
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.11.0
    Uninstalling torchaudio-2.11.0:
      Successfully uninstalled torchaudio-2.11.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
cudf-cu12 26.2.1 requires cuda-toolkit[nvcc,nvrtc]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.5.2 which is incompatible.
datasets 4.8.5 requires fsspec[http]<=2026.2.0,>=2023.1.0, but you have fsspec 2026.7.0 which is incompatible.
gcsfs 2025.12.0 requires fsspec==2025.12.0, but you have fsspec 2026.7.0 which is incompatible.
cuml-cu12 26.2.0 requires cuda-toolkit[cublas,cufft,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
libraft-cu12 26.2.0 requires cuda-toolkit[cublas,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
libcuvs-cu12 26.2.0 requires cuda-toolkit[cublas,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
Successfully installed MarkupSafe-3.0.3 filelock-3.32.3 fsspec-2026.7.0 jinja2-3.1.6 mpmath-1.3.0 networkx-3.6.1 numpy-2.5.2 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-cusparselt-cu12-0.6.2 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 pillow-12.3.0 setuptools-78.1.0 sympy-1.13.1 torch-2.6.0+cu124 torchaudio-2.6.0+cu124 torchvision-0.21.0+cu124 triton-3.2.0 typing-extensions-4.16.0

In [21]:
from langchain_huggingface import HuggingFaceEmbeddings

device = "cuda" if torch.cuda.is_available() else "cpu"

# Инициализация модели через обертку LangChain
embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2",
    model_kwargs={'device': device}
)

sentences = [
    "The Sentences Transformers library provides an easy and open-source way to create embeddings.",
    "Sentences can be embedded one by one or as a list of strings.",
    "Embeddings are one of the most powerful concepts in machine learning!",
    "Learn to use embeddings well and you'll be well on your way to being an AI engineer."
]

# Команда embed_documents() принимает весь список строк
embeddings = embedding_model.embed_documents(sentences)
embeddings_dict = dict(zip(sentences, embeddings))

for sentence, embedding in embeddings_dict.items():
    print("Sentence:", sentence)
    print("First 5 elements:", embedding[:5])
    print("")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Sentence: The Sentences Transformers library provides an easy and open-source way to create embeddings.
First 5 elements: [-0.020798111334443092, 0.03031647950410843, -0.02012181468307972, 0.06864837557077408, -0.025525527074933052]

Sentence: Sentences can be embedded one by one or as a list of strings.
First 5 elements: [0.04317181184887886, -0.05387009680271149, -0.03780446946620941, 0.042723555117845535, -0.023540936410427094]

Sentence: Embeddings are one of the most powerful concepts in machine learning!
First 5 elements: [-0.029861142858862877, -0.013752218335866928, -0.047540176659822464, 0.02721269056200981, 0.03400547802448273]

Sentence: Learn to use embeddings well and you'll be well on your way to being an AI engineer.
First 5 elements: [-0.02207307144999504, 0.02089507132768631, -0.060300540179014206, 0.008439459837973118, 0.043765101581811905]

In [24]:
single_sentence = "Yo! How cool are embeddings?"
single_embedding = embedding_model.embed_query(single_sentence)
print(f"Sentence: {single_sentence}")
print(f"Embedding:\n{single_embedding}")
import torch
print(f"Embedding size: {torch.tensor(single_embedding).shape}")

Sentence: Yo! How cool are embeddings?
Embedding:
[-0.019744746387004852, -0.004510872531682253, -0.004984834231436253, 0.06554446369409561, -0.009876725263893604, 0.027283549308776855, 0.036642588675022125, -0.003302215598523617, 0.008500793017446995, 0.008249524980783463, -0.022849710658192635, 0.04024302214384079, -0.05752000957727432, 0.06336924433708191, 0.04432078078389168, -0.04495074599981308, 0.01252842228859663, -0.025201207026839256, -0.035529252141714096, 0.012955871410667896, 0.008670234121382236, -0.019291769713163376, 0.0035563285928219557, 0.01895061321556568, -0.014712822623550892, -0.009398438036441803, 0.007641688920557499, 0.00962190143764019, -0.005989279132336378, -0.03901693597435951, -0.05478247255086899, -0.005674568936228752, 0.011164519935846329, 0.040806759148836136, 1.7631907667237101e-06, 0.009152970276772976, -0.008772614412009716, 0.023938270285725594, -0.023278431966900826, 0.08049995452165604, 0.031917672604322433, 0.005125950090587139, -0.014770842157304287, -0.016252480447292328, -0.060321323573589325, -0.04356895759701729, 0.04512116685509682, -0.017905399203300476, 0.02633671462535858, -0.03478670120239258, -0.008891726844012737, -0.05476749688386917, -0.012437271885573864, -0.023860663175582886, 0.08334968239068985, 0.05712425336241722, 0.011332866735756397, -0.014959494583308697, 0.0920378565788269, 0.027270924299955368, -0.014218590222299099, 0.019120924174785614, 0.014996330253779888, -0.03121987357735634, 0.08995797485113144, 0.04511883109807968, 0.02580200880765915, -0.00551743246614933, 0.01159098744392395, 0.04721007123589516, -0.01510185282677412, 0.01708184741437435, -0.007225994486361742, 0.034576330333948135, -0.008764705620706081, 0.05220169946551323, -0.06490088254213333, -0.04313788563013077, 0.06369643658399582, 0.04028812050819397, -0.019904308021068573, 0.00539062824100256, 0.012882063165307045, -0.048125527799129486, 0.04588015377521515, -0.021709445863962173, 0.018920356407761574, -0.03463444486260414, -0.016645751893520355, 0.0076516796834766865, -0.022669341415166855, -0.019645439460873604, 0.01876324787735939, 0.010138312354683876, 0.06854133307933807, -0.005398494191467762, -0.0033822976984083652, 0.04084130749106407, 0.04986237734556198, -0.011648574844002724, 0.08917390555143356, 0.040278561413288116, -0.003647153964266181, 0.043775856494903564, -0.029607947915792465, -0.005537547171115875, -0.02002088911831379, -0.02019835263490677, 0.04598492383956909, 0.022933749482035637, -0.053730543702840805, -0.0319279208779335, 0.0013754217652603984, 0.0625036433339119, -0.02183089591562748, -0.06432555615901947, -0.02247917652130127, 0.03319548815488815, -0.03128373622894287, 0.051793668419122696, -0.028400268405675888, 0.02550675719976425, 0.03364931046962738, 0.07506676763296127, -0.0044647809118032455, -0.04877055808901787, -0.07352187484502792, -0.05463530495762825, 0.008885332383215427, 0.029579700902104378, -0.00995700154453516, -0.006327638402581215, 0.04462597519159317, -0.015848413109779358, -0.017133023589849472, 0.03366025164723396, -0.0015767059521749616, -0.05459718778729439, 0.029116161167621613, -0.02805963158607483, 0.02967933937907219, 0.051215339452028275, 0.014876633882522583, -0.04764889180660248, 0.012605198659002781, 0.0014984509907662868, 0.013320683501660824, -0.028246857225894928, -0.03292547166347504, -0.008535711094737053, -0.0527607724070549, 0.07293503731489182, -0.06418213248252869, -0.0025178652722388506, -0.009026368148624897, -0.0011047067819163203, 0.01575147919356823, 0.04308236017823219, 0.011226938106119633, -0.035458531230688095, 0.04951636493206024, 0.012127110734581947, 0.001663433969952166, -0.005069235805422068, -0.011100179515779018, -0.008669198490679264, -0.03264402598142624, -0.03980217128992081, -0.020597105845808983, 0.010907421819865704, -0.06625291705131531, 0.037170667201280594, -0.03749164566397667, -0.032473184168338776, 0.05859000235795975, 0.08480808883905411, 0.0392412468791008, 0.031581420451402664, 0.03783867508172989, -0.013547243550419807, 0.05950627103447914, 0.02589048631489277, -0.013190017081797123, 0.06305902451276779, 0.03271370753645897, 0.006921406835317612, -0.014260673895478249, 0.07766769826412201, -0.011610357090830803, -0.03664277866482735, -0.028383754193782806, 0.027227995917201042, 0.02493651583790779, -0.0042229765094816685, -0.036310065537691116, -0.02048879861831665, 0.03988609090447426, -0.026472754776477814, 0.004413835238665342, -0.05196351557970047, 1.714206337055657e-05, 0.0481284037232399, 0.02044503018260002, 0.09849703311920166, 0.036826785653829575, 0.015340506099164486, 0.0007509761489927769, -0.0338638573884964, -0.026987258344888687, 0.04724454879760742, 0.045670218765735626, -0.034924618899822235, -0.011877025477588177, 0.003455794882029295, -0.006323002744466066, -0.047841209918260574, 0.01840987801551819, -0.022315729409456253, -0.0370728000998497, 0.05873401090502739, 0.006227297708392143, -0.014671615324914455, 0.07292237132787704, 0.002219588728621602, -0.06531193852424622, 0.03516796603798866, -0.015490165911614895, 0.06014213711023331, -0.009410032071173191, 0.02811964973807335, -0.011265158653259277, 0.0005241709877736866, 0.10188857465982437, -0.05699572339653969, -0.03523606061935425, -0.005204751156270504, -0.008466375060379505, 0.013920890167355537, 0.018078051507472992, -0.1104939728975296, 0.05131169408559799, -0.04364324361085892, 0.028414275497198105, 0.009559393860399723, 0.04280963912606239, -0.039583344012498856, 0.052582886070013046, 0.01928146369755268, 0.0034488909877836704, -0.01768709160387516, 0.03856992349028587, 0.006925086956471205, -0.03594405949115753, -0.026361307129263878, -0.004966918844729662, 0.04245259612798691, -0.04224640876054764, 0.0034589990973472595, 0.03558668866753578, -0.016820184886455536, 0.03543310984969139, 0.0045279948972165585, 0.006462852004915476, -0.021771086379885674, -0.025003349408507347, 0.014141819439828396, 0.015125793404877186, -0.029957013204693794, -0.03942273184657097, 0.018782177940011024, -0.0016878371825441718, -0.0009835069067776203, -0.03263215348124504, 0.0050656553357839584, -0.008904606103897095, -0.0155095299705863, 0.01877581514418125, -0.04524729773402214, -0.017295701429247856, 0.03509734943509102, 0.013301820494234562, 0.010063296183943748, -0.04365937039256096, -0.016861917451024055, -0.01910480298101902, 0.06354889273643494, 0.008083250373601913, -0.010253292508423328, -0.004536252468824387, -0.04608360677957535, -0.016470452770590782, -0.006246883887797594, 0.02588684856891632, -0.06390641629695892, -0.007823975756764412, -0.02360759861767292, 0.027461746707558632, 0.058053549379110336, -0.034074898809194565, 0.06460121273994446, 0.020006295293569565, -0.021493569016456604, 0.01693609170615673, -0.005540661979466677, -0.024039719253778458, 0.030944420024752617, -0.0023444106336683035, 0.030259007588028908, -0.04572178050875664, 0.020064150914549828, -0.02571171522140503, -0.001133786397986114, -0.035752471536397934, 0.06929532438516617, 0.0028084320947527885, 0.03587422892451286, -0.015272240154445171, -0.03415234014391899, 0.01809230074286461, 0.016539987176656723, 0.01317056454718113, -0.006366762798279524, 0.054930366575717926, 0.008473156951367855, -0.042607735842466354, 0.02170853316783905, -0.04890238866209984, 0.00011892020847881213, 0.05162865296006203, 0.0007592169567942619, 0.01592227816581726, -0.016130026429891586, 0.014498148113489151, 0.021950900554656982, 0.03026515804231167, -0.03441513702273369, -0.048038024455308914, -0.037169091403484344, 0.04681943729519844, -0.03462190926074982, 0.0004748188948724419, -0.04348203167319298, -0.018012486398220062, -0.06448450684547424, -0.02669675089418888, 0.03636608272790909, -0.03762190788984299, -0.016460111364722252, 0.022024905309081078, 0.0002160213771276176, 0.036451030522584915, -0.027613556012511253, -0.00587058998644352, 0.006973175331950188, -0.0012586412485688925, 0.021277353167533875, 0.006214676890522242, -0.035721391439437866, -0.050936706364154816, 0.028555329889059067, 0.06488217413425446, 0.034573137760162354, -0.025728091597557068, 0.004525545984506607, -0.046360570937395096, 0.033222563564777374, 0.0016997935017570853, -0.012935481034219265, -0.030373459681868553, 0.012360939756035805, -0.00031795771792531013, 0.01662321761250496, 0.010489181615412235, 0.017154071480035782, 0.01888607069849968, -0.03622567653656006, 0.04657367616891861, 0.021712923422455788, 0.04975367337465286, 0.030306750908493996, 0.001599157229065895, -0.06300245970487595, -0.006345886737108231, 0.00010730409121606499, -0.005567454732954502, 0.023726461455225945, -0.008382344618439674, 0.05388973280787468, -0.09089766442775726, -0.013735956512391567, 0.011845417320728302, 0.003372675972059369, -0.028185520321130753, 0.0015633127186447382, 0.022241542115807533, 0.062102433294057846, -0.0868120789527893, -0.0044063543900847435, -0.016399569809436798, 0.016966508701443672, -0.013454829342663288, 0.0030070350039750338, -0.021461790427565575, -0.020950395613908768, -0.013987828977406025, -0.012385040521621704, 0.0539979487657547, 0.060361530631780624, 0.0252982210367918, -0.1296614408493042, -0.1080816239118576, -0.00415775366127491, -0.007202702574431896, 0.02758852392435074, 0.0487622432410717, -0.029597144573926926, -0.043255455791950226, 0.027521491050720215, 0.013571876101195812, 0.038770031183958054, 0.02420399896800518, -0.027084242552518845, 0.08591659367084503, -0.019840260967612267, -0.022634368389844894, -0.06249278038740158, -0.015684468671679497, 0.041156649589538574, 0.01669527217745781, 0.07972913980484009, -0.032483913004398346, 0.0014656338607892394, -0.03279059752821922, 0.06448154151439667, 0.020973917096853256, -0.07569847255945206, -0.0013179582310840487, 0.002240448258817196, -0.006608382798731327, -0.06842523068189621, -0.005368590820580721, 0.06551355868577957, 0.005455703474581242, 0.01589931547641754, -0.0218051765114069, 0.00216418644413352, 0.004729557316750288, -0.0725654810667038, -0.01593507081270218, -0.010562284849584103, 0.027078667655587196, 0.0019377091666683555, -0.04451224207878113, 0.02897830866277218, 0.024308359250426292, -0.017388563603162766, -0.03806693106889725, -0.030679920688271523, -0.032477837055921555, -0.00043331689084880054, 0.025584647431969643, 0.027047859504818916, -0.0001724694448057562, -0.0004936830373480916, -0.07120940834283829, 0.05697682499885559, 0.0661400854587555, -0.03872677683830261, -0.013068387284874916, 0.010066352784633636, -0.02177402935922146, 0.019221249967813492, 0.007666930556297302, -0.038665253669023514, -0.016610927879810333, -0.03414679691195488, -0.010418621823191643, 0.017590634524822235, -0.01237765233963728, -0.01684337481856346, -0.02401132509112358, 0.004701956175267696, 0.004884565249085426, 0.04736632481217384, 0.04341119900345802, -0.008083405904471874, -0.024827226996421814, -0.019397804513573647, -0.03165257349610329, -0.015641868114471436, -0.007799455430358648, 0.012888781726360321, 0.02619434893131256, 0.0036582842003554106, 0.0579228401184082, 0.054315175861120224, -0.05055874213576317, 0.0017892351606860757, -0.024547113105654716, -0.024759624153375626, 0.003603532677516341, 0.01941526308655739, -0.04238228127360344, -0.018690727651119232, 0.023294629529118538, -0.03179827705025673, -0.026064550504088402, -0.005403618328273296, -0.038207001984119415, 0.022171957418322563, 0.013336054049432278, 0.05580541118979454, -0.0357716828584671, -0.03547912836074829, 0.012772338464856148, 0.06801780313253403, 0.05371523275971413, 0.025415154173970222, -0.011663893237709999, -0.010751251131296158, -0.009744280017912388, 0.007205070927739143, 0.009219033643603325, -0.04736850783228874, -0.003893941640853882, 0.031145354732871056, 0.036233190447092056, -0.016590308398008347, -0.03633942827582359, 0.01956348679959774, -0.02150593511760235, -0.007047726307064295, 0.009131806902587414, -0.040535859763622284, -0.036707546561956406, 0.11699597537517548, 0.11791384220123291, 0.08005031198263168, -0.01619832217693329, -0.020073292776942253, -0.055406130850315094, -0.07224106788635254, 0.021455761045217514, -0.0004464302910491824, -0.014290346764028072, 0.008355440571904182, 0.033420711755752563, 0.014289136044681072, 0.04625127837061882, -0.03534204512834549, 0.016867373138666153, -0.0029974172357469797, -0.05449971556663513, -0.0480719693005085, 0.0009475721162743866, -6.297215807535121e-33, -0.02302863448858261, -0.02511277049779892, -0.05352194234728813, -0.020947011187672615, -0.0067971632815897465, -0.04640159010887146, -0.004496312700212002, 0.01651148870587349, -0.011267772875726223, 0.013301349245011806, -0.01725527085363865, -0.01966530829668045, 0.005532350856810808, 0.010277564637362957, 0.000947333115618676, -0.022402271628379822, 0.05303647369146347, 0.0077777523547410965, -0.00948471762239933, 0.022551583126187325, -0.00434493413195014, 0.022520869970321655, 0.019808635115623474, -0.07574284821748734, -0.004366790410131216, 0.025082960724830627, 0.025939365848898888, -0.03070765733718872, 0.0704764649271965, 0.08635004609823227, -0.07758805900812149, 0.015999123454093933, -0.050469230860471725, 0.04883550480008125, 0.0037499547470360994, -0.0006129477987997234, -0.0387277714908123, -0.023223549127578735, -0.03639832139015198, -0.005070257466286421, 0.011051795445382595, -0.032651543617248535, 0.03683871403336525, -0.04549494385719299, -0.0011853266041725874, 0.0019269115291535854, 0.021878380328416824, 0.027109302580356598, -0.04062638431787491, 0.06991599500179291, -0.07332814484834671, -0.008152926340699196, -0.0142555832862854, 0.003780327271670103, 0.12097427994012833, -0.06682133674621582, 0.03050519898533821, 0.012448075227439404, -0.04592941328883171, 0.01038730051368475, -0.0397978238761425, -0.013304213061928749, -0.0159402247518301, -0.042934734374284744, 0.04052754491567612, 0.07070741802453995, -0.045092903077602386, -0.03624735772609711, -0.01875888928771019, 0.016092821955680847, 0.021265732124447823, 0.06700263917446136, 0.03258642926812172, 0.015112577937543392, 0.032037146389484406, -0.013543590903282166, 0.023178059607744217, -0.011312524788081646, 0.012379620224237442, -0.03735171630978584, 0.0015554273268207908, 0.02158241905272007, -0.03494419902563095, -0.029769055545330048, 0.023239754140377045, -0.012570268474519253, -0.010943270288407803, -0.08879691362380981, -0.02201838605105877, -0.011842284351587296, -0.057108357548713684, 0.0391809418797493, -0.019882719963788986, -0.05592704936861992, 0.0076034339144825935, 0.022364208474755287, -0.018626701086759567, 0.03798055648803711, -0.0008796086185611784, -0.052619922906160355, 0.002050645649433136, 0.017281509935855865, -0.04840290918946266, -0.018774066120386124, 1.0092482227719302e-07, 0.020659465342760086, 0.03035746142268181, 0.005718594416975975, -0.05339384078979492, -0.02465207315981388, 0.01803414337337017, -0.033997826278209686, 3.4636963391676545e-05, -0.06400352716445923, 0.025004949420690536, -0.02041119709610939, -0.0027204155921936035, -0.03559613600373268, 0.027192292734980583, 0.06489405781030655, 0.0009834496304392815, -0.04384911432862282, -0.044529691338539124, -0.007448805030435324, 0.011520516127347946, -0.0029125388246029615, -0.021549487486481667, 0.002842486836016178, 0.042939912527799606, -0.06090405210852623, -0.007863235659897327, -0.003901244141161442, 2.477183329574473e-07, 0.0007758387946523726, 0.07477366179227829, 0.0019931523129343987, -0.006072232499718666, 0.03692106157541275, 0.02784208580851555, -0.05649004876613617, 0.016105882823467255, -0.009508210234344006, -0.002608537906780839, -0.02457377314567566, 0.019139060750603676, 0.05081959813833237, 0.026125870645046234, -0.10383805632591248, -0.030581586062908173, -0.035334449261426926, -0.040703728795051575, -0.021984228864312172, -0.022409232333302498, 0.05055675655603409, 0.07226072996854782, 0.055478956550359726, 0.0489434152841568, 0.0033795014023780823, -0.06847604364156723, 0.007103202398866415, 0.003156673163175583, 0.047809142619371414, -0.0719795897603035, -0.033030152320861816, 0.03191593289375305, 0.0017643037717789412, -0.04627905413508415, -0.019637959077954292, 0.01674940250813961, 0.04736040160059929, -0.02094411663711071, 0.007102406583726406, 0.04531461000442505, -0.047652337700128555, -0.047488074749708176, 0.010079961270093918, -0.08395948261022568, 0.03369300067424774, -0.037218932062387466, 0.011943232268095016, -0.03168964013457298, -0.0012972642434760928, -0.015554160811007023, 0.018172821030020714, -0.014936885796487331, -0.01706712134182453, -0.04197162762284279, 0.003946586046367884, -0.0224301815032959, 0.020729215815663338, -0.04614154249429703, 0.008502154611051083, -0.025686508044600487, -0.01653381809592247, -0.015184708870947361, -0.010004191659390926, 0.02196424826979637, 0.026110397651791573, 0.07313590496778488, -0.01837095618247986, 1.939794349242208e-34, -0.007279359269887209, 0.0059648980386555195, 0.04443107172846794, 0.04148228466510773, 0.011291741393506527, -0.019321780651807785, 0.04418786242604256, -0.008937890641391277, 0.036112021654844284, -0.055212635546922684, -0.02895723655819893]
Embedding size: torch.Size([768])

In [25]:
%%time

# Uncomment to see how long it takes to create embeddings on CPU
# # Make sure the model is on the CPU
# embedding_model.to("cpu")

# # Embed each chunk one by one
# for item in tqdm(pages_and_chunks_over_min_token_len):
#     item["embedding"] = embedding_model.encode(item["sentence_chunk"])

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 9.54 µs

In [28]:
%%time

# Send the model to the GPU (already configured during initialization in SOYZniusXg0u)
# embedding_model.to("cuda") # requires a GPU installed, for reference on my local machine, I'm using a NVIDIA RTX 4090

# Create embeddings one by one on the GPU
for item in tqdm(pages_and_chunks_over_min_token_len):
    item["embedding"] = embedding_model.embed_query(item["sentence_chunk"])

  0%|          | 0/2029 [00:00<?, ?it/s]

CPU times: user 33.1 s, sys: 208 ms, total: 33.3 s
Wall time: 35 s

In [29]:
# Turn text chunks into a single list
text_chunks = [item["sentence_chunk"] for item in pages_and_chunks_over_min_token_len]

In [30]:
import torch
from langchain_huggingface import HuggingFaceEmbeddings

device = "cuda" if torch.cuda.is_available() else "cpu"

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2",
    model_kwargs={'device': device},
    encode_kwargs={'batch_size': 32}  # Configures batch size for embed_documents
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [31]:
%%time

# Embed all text chunks
raw_embeddings = embedding_model.embed_documents(text_chunks)

# Convert list of embeddings to PyTorch Tensor (equivalent to convert_to_tensor=True)
text_chunk_embeddings = torch.tensor(raw_embeddings, device=device)

text_chunk_embeddings

CPU times: user 19.6 s, sys: 70.7 ms, total: 19.7 s
Wall time: 19.3 s

tensor([[ 0.0479, -0.0243, -0.0130,  ..., -0.0217,  0.0279, -0.0196],
        [ 0.0086,  0.0291, -0.0065,  ...,  0.0695, -0.0112, -0.0391],
        [ 0.0898,  0.0149, -0.0232,  ...,  0.0350, -0.0089, -0.0236],
        ...,
        [ 0.0003, -0.0612, -0.0006,  ...,  0.0386,  0.0054,  0.0093],
        [ 0.0312, -0.0377,  0.0366,  ...,  0.0344, -0.0048, -0.0165],
        [-0.0121, -0.0633,  0.0146,  ...,  0.0535, -0.0086, -0.0019]],
       device='cuda:0')

In [32]:
# Save embeddings to file
text_chunks_and_embeddings_df = pd.DataFrame(pages_and_chunks_over_min_token_len)
embeddings_df_save_path = "text_chunks_and_embeddings_df.csv"
text_chunks_and_embeddings_df.to_csv(embeddings_df_save_path, index=False)

In [33]:
# Import saved file and view
text_chunks_and_embedding_df_load = pd.read_csv(embeddings_df_save_path)
text_chunks_and_embedding_df_load.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding
0,-40,Dune Frank Herbert Copyright 1965 Book 1 DUN...,1382,272,345.50,"[0.04793761298060417, -0.024343056604266167, -..."
1,-40,The old woman was a witch shadow -- hair like ...,558,100,139.50,"[0.00860720593482256, 0.02914559096097946, -0...."
2,-40,"She chuckled. ""But royalty has need of slyness...",281,58,70.25,"[0.08982345461845398, 0.01486481074243784, -0...."
3,-39,"""Sleep well, you sly little rascal,"" said the ...",669,136,167.25,"[0.03215346112847328, 0.05946078151464462, 0.0..."
4,-39,Kwisatz Haderach. There had been so many thi...,932,165,233.00,"[0.04089375585317612, 0.001995265716686845, -0..."

In [37]:
import json
import torch
import pandas as pd

# 1. Запись в CSV с сериализацией через json.dumps
raw_embeddings = embedding_model.embed_documents(text_chunks)
df = pd.DataFrame(pages_and_chunks_over_min_token_len)
df["embedding"] = [json.dumps(emb) for emb in raw_embeddings]

csv_save_path = "text_chunks_and_embeddings_df.csv"
df.to_csv(csv_save_path, index=False)

# 2. Чтение и десериализация через json.loads
df_loaded = pd.read_csv(csv_save_path)
df_loaded["embedding"] = df_loaded["embedding"].apply(json.loads)

# 3. Преобразование в тензор PyTorch
embeddings = torch.tensor(df_loaded["embedding"].tolist(), dtype=torch.float32).to(device)
print(embeddings.shape)

torch.Size([2029, 768])

In [38]:
text_chunks_and_embedding_df.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding
0,-40,Dune Frank Herbert Copyright 1965 Book 1 DUN...,1382,272,345.50,"[0.04793761298060417, -0.024343056604266167, -..."
1,-40,The old woman was a witch shadow -- hair like ...,558,100,139.50,"[0.00860720593482256, 0.02914559096097946, -0...."
2,-40,"She chuckled. ""But royalty has need of slyness...",281,58,70.25,"[0.08982345461845398, 0.01486481074243784, -0...."
3,-39,"""Sleep well, you sly little rascal,"" said the ...",669,136,167.25,"[0.03215346112847328, 0.05946078151464462, 0.0..."
4,-39,Kwisatz Haderach. There had been so many thi...,932,165,233.00,"[0.04089375585317612, 0.001995265716686845, -0..."

In [39]:
embeddings[0]

tensor([ 4.7938e-02, -2.4343e-02, -1.2992e-02,  2.2343e-02, -4.2528e-03,
         3.3806e-02,  3.1966e-02,  8.0231e-03,  4.2489e-02, -1.8211e-02,
         8.4046e-02, -5.4432e-02,  1.5471e-02, -5.5373e-02, -2.6275e-03,
         2.2406e-02,  3.4723e-02, -2.4773e-02, -2.6130e-02,  1.9207e-02,
        -2.7781e-02,  4.8479e-03,  2.7200e-02,  9.3811e-03,  1.3458e-01,
        -1.2687e-02,  5.5638e-03,  8.1027e-03,  1.0328e-02, -1.4904e-02,
        -1.2637e-02, -1.1670e-02,  4.2506e-02, -2.7154e-02,  2.5789e-06,
        -4.6621e-02, -1.6685e-02, -3.8757e-02,  2.2177e-02, -1.0823e-02,
         3.4653e-02,  6.7642e-03, -1.6383e-02, -1.9323e-02,  1.8612e-02,
        -5.0098e-02,  2.1515e-02,  3.4432e-02, -2.6360e-02,  1.3497e-02,
         9.3486e-03, -5.3976e-02, -3.3663e-02,  8.3128e-03,  1.6931e-02,
         5.1280e-02, -2.2205e-03,  2.7144e-02,  8.0904e-03,  2.8443e-02,
        -1.9645e-02,  1.4887e-02, -4.0106e-02, -5.3086e-03,  1.2802e-01,
        -4.3501e-02, -1.8083e-02,  1.4957e-02,  2.9505e-02, -4.7872e-03,
         2.4140e-02, -2.9323e-02, -6.6350e-03,  3.2403e-02, -5.4761e-02,
         5.9693e-03,  2.1793e-02,  5.5030e-02, -3.8684e-02,  2.8686e-02,
         2.3208e-02, -1.9396e-02, -1.1587e-02, -1.1475e-02,  2.4416e-02,
         3.9556e-02, -2.7911e-02,  1.0697e-02,  5.1416e-02, -3.2523e-02,
        -1.4516e-02, -1.8968e-02, -1.1351e-02,  1.0456e-02,  6.1253e-03,
         6.9408e-03, -4.2723e-03, -1.2689e-02,  2.3304e-02,  1.8597e-02,
         1.7717e-02,  2.2406e-02,  5.5171e-02,  1.9899e-02, -5.7797e-02,
        -1.8343e-02,  4.4841e-02, -5.0540e-02,  1.9789e-02,  3.9287e-04,
         3.4621e-02,  1.4851e-02, -2.9735e-02,  2.8789e-03,  8.5033e-03,
        -6.1277e-03, -3.5055e-03, -5.6539e-02,  9.0104e-02,  1.5278e-03,
        -2.5741e-02, -2.8625e-02, -4.3630e-02, -2.3975e-03, -1.3334e-02,
        -6.3513e-02, -2.4747e-02, -2.9701e-02,  1.9849e-03, -4.2274e-02,
        -1.0560e-02, -4.9366e-03, -7.3585e-03,  1.0025e-02, -1.9071e-02,
         6.3984e-02,  1.9680e-02, -8.8163e-03, -4.8908e-02,  5.8527e-02,
         1.3199e-02,  2.2176e-02,  1.9473e-02,  8.8560e-03,  3.1836e-02,
         1.0446e-02, -1.1941e-03,  6.6489e-03, -1.5247e-03,  9.1439e-03,
         6.3049e-02,  5.1020e-02,  2.5460e-02,  1.6380e-02,  1.9934e-02,
         7.3231e-02, -2.7498e-02, -3.5954e-02,  6.0488e-02, -1.2582e-02,
        -1.8962e-02, -1.5776e-02,  1.0003e-02, -2.2050e-02, -7.0077e-03,
         3.7003e-02,  4.9712e-02, -4.1621e-03,  1.8221e-02,  9.3628e-04,
        -5.6828e-02, -4.7183e-02,  5.1439e-03,  2.6910e-02, -3.7597e-02,
        -3.6606e-02, -5.4604e-02,  3.7753e-02, -1.8515e-02,  6.9429e-02,
         4.4714e-03, -1.0980e-02,  8.4046e-02,  2.7126e-03,  5.7632e-02,
        -1.9588e-02, -2.7482e-02,  2.8376e-02,  3.2959e-02,  2.8040e-02,
         2.2713e-02, -3.2742e-03, -1.0645e-03,  5.9991e-03, -1.1733e-02,
         2.9764e-02,  4.5737e-02,  1.1371e-02,  6.4227e-04, -2.7328e-02,
         3.8954e-03,  6.1177e-02,  3.6586e-02, -5.5206e-02, -5.4392e-03,
        -3.9805e-02,  1.9194e-02, -3.8192e-02,  5.9263e-02, -2.3117e-02,
         7.3942e-02,  3.6403e-02,  1.1529e-02, -7.4937e-02,  9.0586e-03,
        -8.7183e-03,  1.3557e-03,  4.4029e-02, -6.0285e-02, -1.6034e-02,
         1.7625e-02,  2.5672e-02,  4.0381e-03, -2.0749e-03, -7.9520e-02,
        -6.6908e-02, -7.8713e-03, -2.4571e-02,  1.7798e-02, -3.8583e-02,
        -2.6085e-02,  1.0289e-02,  1.7841e-04, -5.2501e-02, -3.8792e-02,
         1.9532e-02,  2.5945e-03,  1.0021e-01, -1.4618e-02, -1.8152e-02,
         2.7839e-02,  1.0794e-02,  4.0218e-02, -7.8167e-03,  1.6549e-02,
         9.1636e-03, -1.1488e-03,  1.6521e-02,  6.2197e-02, -7.3706e-03,
         1.1495e-02, -4.0227e-03, -1.4384e-02,  2.0450e-02,  7.5660e-02,
        -1.7997e-02, -1.4082e-02,  3.3551e-02,  4.2499e-02,  1.2631e-02,
        -2.7706e-02,  1.4476e-02, -4.8062e-02, -7.4396e-03, -3.4377e-02,
         2.7176e-02, -5.2434e-02,  3.8538e-02, -2.9997e-02,  1.6689e-02,
        -1.7379e-02, -4.6338e-03,  2.8351e-02,  1.0337e-02, -1.2335e-04,
        -1.9091e-02, -2.6688e-02,  2.3024e-02, -2.5113e-02, -2.7386e-02,
         3.3541e-02,  3.1080e-02, -2.0938e-02,  3.6491e-02,  8.1975e-05,
         7.2837e-02,  3.7098e-02, -1.0004e-01, -6.6354e-02, -8.1871e-02,
         4.9341e-03,  3.9103e-03, -5.0327e-02,  6.3723e-02,  8.6184e-03,
        -4.4999e-03,  5.7217e-02, -2.1857e-02, -4.7233e-02,  8.3114e-02,
         1.8775e-02, -3.5323e-03, -1.8614e-02, -3.5711e-03,  4.5578e-02,
        -1.7642e-02,  9.9453e-03, -1.9973e-02, -3.0681e-02, -2.6282e-02,
        -1.3302e-02, -1.3766e-02,  3.7539e-02,  4.1580e-02, -3.9143e-03,
         5.9429e-03,  3.6835e-02, -3.0132e-02,  5.5843e-03,  5.7624e-02,
        -5.8389e-03,  9.9968e-03,  4.7769e-03,  6.4986e-03, -4.1535e-02,
        -4.3639e-02,  4.5964e-02,  2.7345e-03, -1.1045e-02,  1.0823e-02,
         2.5954e-02,  5.5783e-02, -6.2416e-04, -2.9540e-02,  4.4898e-02,
        -3.2269e-02,  3.9595e-03, -1.8948e-02, -1.7848e-02, -4.2138e-02,
        -2.6274e-02, -3.5919e-02, -1.2906e-02,  6.2487e-03, -5.5457e-02,
         5.3467e-03, -2.0369e-02, -4.6665e-03, -5.9011e-02, -7.6906e-02,
        -5.9383e-03, -1.2924e-02,  5.5751e-03,  8.2544e-03,  7.8755e-03,
        -2.7917e-02,  6.0542e-02, -2.6350e-02,  6.9575e-02, -9.1292e-03,
         2.1820e-02,  2.7112e-02, -8.8997e-02,  1.4247e-03, -7.9283e-04,
         3.0687e-03,  3.8087e-02, -9.9671e-03,  1.3496e-02, -2.8023e-02,
         5.7437e-02, -1.0965e-02, -2.4286e-02,  2.6261e-02,  1.4225e-02,
         3.8885e-03,  3.4868e-03, -1.6523e-02,  4.1440e-03,  3.7552e-02,
         2.5692e-03, -1.0582e-02,  7.1645e-03,  2.1965e-02,  9.7811e-03,
         7.3951e-03, -2.6092e-03,  3.4165e-03,  2.0819e-02, -1.0333e-03,
         1.1330e-02, -1.8460e-02, -5.6189e-04,  1.4104e-02, -8.4584e-03,
        -8.8028e-03, -9.4595e-02, -3.0023e-02,  1.3764e-02, -7.2183e-03,
        -3.3687e-03,  1.1588e-01,  9.0281e-02,  1.2463e-02, -4.1894e-02,
         8.4765e-02,  4.4391e-03, -6.6510e-03,  2.3796e-02, -2.9815e-02,
         1.3636e-02, -6.0363e-03, -7.4747e-04,  3.4688e-02, -3.7540e-02,
         2.1654e-02, -1.1764e-03, -3.4979e-02, -1.8549e-02, -1.2501e-02,
         9.3235e-03, -1.5965e-02, -2.8243e-02, -2.2610e-02,  4.3294e-02,
         9.7234e-03,  6.4949e-02, -5.7558e-03, -1.1304e-02,  1.2451e-02,
        -1.5609e-03, -6.6855e-02, -4.8127e-02,  2.0478e-02, -3.0539e-02,
         1.7245e-03, -4.2641e-02,  7.6858e-03,  1.6364e-02, -3.4009e-03,
        -3.1226e-02, -2.0250e-02, -1.1786e-02,  5.7756e-02, -5.0241e-02,
         7.1980e-02,  3.4720e-02, -6.9547e-02, -1.3421e-02, -2.8124e-02,
        -1.4478e-02,  2.0267e-02, -4.9668e-02, -2.4942e-02, -6.2084e-02,
         2.9950e-02, -1.9260e-02, -9.1789e-02, -1.4104e-02,  1.5343e-02,
        -2.2191e-02,  2.1430e-02, -1.0359e-03, -1.0797e-02, -3.2207e-02,
        -8.7487e-02, -1.3601e-01, -2.0242e-02,  3.3280e-02, -5.1255e-02,
        -4.0026e-02, -4.6562e-02,  2.8410e-02,  1.9526e-02,  5.0324e-02,
        -9.4190e-03, -2.5456e-02,  9.6556e-03, -3.8734e-02, -3.1539e-02,
        -7.5890e-02,  1.4941e-02, -6.1201e-02, -3.4294e-02, -1.3998e-02,
        -1.0106e-01, -2.2577e-03,  2.0212e-02, -4.7041e-02,  3.7253e-02,
         2.9035e-04, -1.3436e-02, -1.7720e-02,  1.7900e-02,  7.6978e-03,
         5.8027e-03,  3.9486e-02, -3.3014e-02,  4.1663e-02,  1.8890e-02,
        -1.6880e-02, -7.4375e-03, -1.1672e-02, -4.7974e-02, -1.5979e-02,
        -4.4078e-02,  3.4000e-02, -9.4513e-03, -2.7916e-02,  1.5137e-02,
        -1.3255e-02,  1.0045e-02, -6.2863e-03, -4.4525e-02, -1.8629e-02,
        -9.9805e-03, -1.2614e-02, -6.9089e-02,  3.9277e-02,  1.6411e-03,
         7.6461e-03,  1.1770e-02, -1.5520e-02, -1.3226e-02, -9.8139e-03,
        -3.1478e-02,  2.7051e-02,  3.0031e-03,  6.4899e-02,  1.7550e-02,
        -3.2064e-03, -2.8013e-02,  4.1998e-02, -2.2706e-02,  5.7804e-03,
         6.7897e-03, -5.3165e-02, -2.4378e-04, -2.1261e-02,  2.6830e-02,
         2.4136e-02, -1.0381e-02, -2.4768e-02,  3.6672e-02,  1.6202e-02,
         6.1696e-02, -3.2542e-02,  1.5947e-02, -1.6865e-02, -7.7900e-02,
        -4.2386e-02,  4.8608e-02, -4.7430e-02, -2.6455e-02,  2.0560e-02,
        -6.8602e-33, -3.2952e-02,  2.7732e-02, -4.1828e-03,  5.1712e-02,
        -9.3855e-03, -6.5505e-02, -2.4363e-03,  2.8055e-02, -5.7595e-02,
        -2.8393e-02,  3.0525e-02,  1.9724e-02, -1.0431e-02, -1.8006e-02,
         6.0659e-02,  1.8035e-02,  5.1257e-03, -1.3191e-02, -1.9549e-03,
        -2.4499e-02, -2.3846e-02,  7.9451e-03,  2.9022e-02, -8.3671e-02,
         5.3851e-02, -2.7570e-02, -4.8499e-02, -2.7650e-02, -4.9002e-02,
         1.7681e-03, -3.1784e-02, -3.2190e-02,  1.8548e-02, -9.4070e-02,
         3.6498e-03,  1.9968e-03, -5.3417e-02,  5.5697e-02,  2.1125e-02,
         4.6470e-02,  6.3097e-02, -7.7048e-02, -7.3914e-02, -3.6872e-02,
         4.2010e-02, -1.4783e-02,  1.0271e-02, -1.1648e-02, -3.4781e-02,
        -5.2242e-02, -3.7133e-02, -3.7755e-02, -2.8604e-02, -1.5529e-02,
        -6.2794e-04,  4.5537e-02,  1.7111e-02,  6.5265e-02, -2.4946e-02,
         5.6302e-03,  4.6629e-02, -1.2300e-02, -5.4809e-02,  8.5234e-03,
         1.0838e-02,  4.2077e-02,  7.6912e-02,  4.9313e-02,  2.4791e-02,
         4.6895e-02, -1.6680e-02, -7.6321e-02, -4.4109e-02,  4.9626e-03,
         5.4293e-02,  3.1930e-04,  1.4373e-02, -1.1870e-03, -3.6761e-02,
        -1.8185e-02,  1.8630e-02, -1.5664e-02, -3.9974e-02,  1.9135e-02,
         4.5561e-02,  4.7996e-02,  8.7905e-03,  7.8759e-02, -9.7320e-03,
        -1.1342e-03,  4.9775e-02,  6.2933e-02, -3.6586e-02, -2.3479e-02,
         1.2650e-02, -2.2026e-02,  1.3869e-02,  1.8333e-02,  2.3301e-02,
         2.7643e-02,  8.8085e-02, -5.3710e-02, -2.3435e-02, -2.9598e-02,
         4.2416e-02,  1.2193e-03,  1.1599e-02, -5.1933e-02, -8.4901e-02,
        -3.9784e-02, -4.8460e-03, -2.8837e-02, -3.4222e-03,  1.0018e-01,
        -4.5206e-02, -4.0205e-02,  1.0347e-02,  6.5633e-02, -4.9511e-03,
         3.6741e-02,  1.4722e-02,  2.6967e-02,  1.8713e-02, -2.8860e-02,
         1.4197e-02,  2.3417e-02, -3.4398e-02,  3.9691e-02, -2.3865e-02,
         2.4250e-02, -2.9204e-02,  1.3693e-02,  3.2757e-07,  9.6971e-03,
         8.4099e-03, -2.4502e-02, -8.1238e-02,  5.4784e-03,  3.3937e-03,
        -4.3450e-03,  1.4497e-02,  1.1501e-02,  4.8118e-02, -7.3234e-03,
        -1.9412e-02, -1.0116e-02, -3.3067e-02, -5.8941e-02, -5.5844e-02,
         1.4541e-03, -2.4692e-02, -2.5502e-02, -5.7058e-02,  4.5537e-02,
         5.7610e-02, -1.6650e-02,  6.7878e-03,  2.0922e-02,  1.9878e-02,
        -8.3192e-03, -2.7549e-02,  5.4789e-02,  2.4956e-02,  5.0747e-02,
        -4.0658e-02, -4.4938e-03, -3.4044e-02,  1.4328e-02, -6.0549e-02,
         3.6646e-02,  5.7714e-02,  5.3923e-02,  3.3472e-02,  1.1736e-02,
         3.9060e-02, -6.9978e-03, -2.3053e-02, -5.7147e-02,  1.1274e-01,
         1.9666e-02,  6.9755e-03,  1.1824e-02,  1.3994e-02,  3.3436e-02,
         4.9141e-02,  1.9782e-02, -2.7763e-02, -9.6393e-04, -2.2919e-02,
         4.3422e-02,  5.1734e-03,  5.4478e-03,  4.2247e-02, -1.9496e-02,
         7.6016e-02,  4.8964e-02, -1.0438e-01,  2.6953e-02, -1.1246e-01,
         1.9516e-02,  3.1083e-34, -1.9619e-02, -2.3787e-02,  1.8742e-02,
        -5.4684e-02,  4.5732e-03, -4.5566e-03,  3.3275e-02,  6.1062e-03,
        -2.1693e-02,  2.7874e-02, -1.9600e-02], device='cuda:0')